# Generated by Django 4.0.5 on 2022-06-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
                ('imgurl', models.CharField(max_length=256)),
                ('runningtime', models.CharField(blank=True, max_length=64, null=True)),
                ('opendate', models.CharField(blank=True, max_length=64, null=True)),
                ('actors', models.CharField(blank=True, max_length=256)),
                ('age', models.CharField(max_length=64)),
                ('story', models.TextField(blank=True, null=True)),
                ('genre', models.ManyToManyField(to='movie.genremodel')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
