# Generated by Django 4.0.5 on 2022-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user_rate', models.FloatField()),
                ('movie_rate', models.FloatField(null=True)),
                ('post_img', models.ImageField(upload_to='')),
                ('actor', models.CharField(max_length=256)),
                ('desc', models.TextField(null=True)),
                ('movie_genre', models.ManyToManyField(to='movie.genremodel')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
