# Generated by Django 4.0.5 on 2022-06-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('openDate', models.CharField(max_length=100)),
                ('rate', models.FloatField(null=True)),
                ('participate', models.FloatField(null=True)),
                ('actors', models.CharField(max_length=256)),
                ('story', models.TextField(null=True)),
                ('post_img', models.ImageField(upload_to='')),
                ('genre', models.ManyToManyField(to='movie.genremodel')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
