# Generated by Django 4.0.5 on 2022-06-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genremodel',
            name='content',
        ),
    ]
