# Generated by Django 4.0.5 on 2022-06-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='actors',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='openDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='participate',
            field=models.FloatField(blank=True),
        ),
    ]
