# Generated by Django 4.0.5 on 2022-06-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genremodel',
            old_name='genre',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='movie_genre',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='movie_rate',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='post_img',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='user_rate',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='actors',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='age',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='imgurl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='opendate',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='runningtime',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
