# Generated by Django 4.0.5 on 2022-06-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemodel',
            old_name='genre',
            new_name='genre_name',
        ),
    ]
