# Generated by Django 3.2.5 on 2022-06-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviecomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='movie.GenreModel'),
        ),
    ]
