# Generated by Django 4.0.5 on 2022-06-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_genremodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genremodel',
            name='genre_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
