# Generated by Django 4.0.5 on 2022-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_genre_moviemodel_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='age',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='genre_name',
            field=models.ManyToManyField(blank=True, null=True, to='movie.genremodel'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='imgurl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
