# Generated by Django 4.0.5 on 2022-06-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_genremodel_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='movie_genre',
            field=models.ManyToManyField(to='movie.genremodel'),
        ),
    ]
