# Generated by Django 4.0.5 on 2022-06-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_moviemodel_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='openDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='participate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
