# Generated by Django 4.0.5 on 2022-06-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_moviemodel_age_alter_moviemodel_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='actors',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
