# Generated by Django 3.2.5 on 2022-06-12 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_movielike'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='like_user',
            field=models.ManyToManyField(related_name='like_movie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MovieLike',
        ),
    ]
