# Generated by Django 4.0.5 on 2022-06-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_moviemodel_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genremodel',
            old_name='genre_name',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='post',
            new_name='post_img',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='naver_rate',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='story',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='movie_rate',
            field=models.FloatField(null=True),
        ),
    ]
