# Generated by Django 4.0.5 on 2022-06-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_rename_genre_genremodel_genre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
