# Generated by Django 4.0.5 on 2022-06-09 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='genre_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.genremodel'),
        ),
    ]
