# Generated by Django 4.0.5 on 2022-06-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_genre_name_genremodel_genre_and_more'),
        ('user', '0002_rename_genre_usermodel_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='genre_name',
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.ForeignKey(choices=[('action', 'action'), ('romance', 'romance')], null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.genremodel')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profiles',
            field=models.ManyToManyField(to='user.profilemodel'),
        ),
    ]
