# Generated by Django 4.0.5 on 2022-06-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_genre_name_genremodel_genre_and_more'),
        ('user', '0004_alter_profilemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.genremodel'),
        ),
    ]
