# Generated by Django 4.0.5 on 2022-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_genre_name_genremodel_genre_and_more'),
        ('user', '0005_alter_profilemodel_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='genre',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='genre',
            field=models.ManyToManyField(null=True, to='movie.genremodel'),
        ),
    ]
