# Generated by Django 4.0.5 on 2022-06-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profilemodel_genre_profilemodel_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='name',
            new_name='profilename',
        ),
    ]
